apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-0
  storageClassName: postgres-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-1
  storageClassName: postgres-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-2
  storageClassName: postgres-storage
---
