# Create a PersistentVolume with Specific Specifications:
# name: data-volume
# capacity: 10Gi
# accessModes: ReadWriteOnce
# storageClass: fast-storage
# hostPath: /mnt/data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: fast-storage
  hostPath:
    path: /mnt/data
